# Setup
title: Gyuwon's Blog
description:  Yesterday is history.  
              Tomorrow is mystery.  
              But today is a present.  
              It is called the present.
url: https://gyuwonsong.github.io/july22.github.io/
avatar: /profile.jpg
paginate: 5
permalink: pretty
cover_image: /profile2.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: vszhub
  card: summary
logo: logo.png
social:
  name: Songzi Vong
  links:
    - https://www.instagram.com/july.22days/
    - https://www.facebook.com/profile.php?id=100008277976591
    - https://github.com/gyuwonsong
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Gyuwon Song
  url: https://github.com/gyuwonsong
  email: gyuwon0722@kookmin.ac.kr